import tkinter 
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler 
from Machine import Classifier  
clas=Classifier()
svm=clas.svm_grid()
window=tkinter.Tk()
window.geometry("800x800")
label_head=tkinter.Label(text="Loan Prediction System",font=("arial",30),borderwidth=0)
label_head.pack()
my_var=tkinter.IntVar()
my_var1=tkinter.IntVar()
my_var2=tkinter.IntVar()
my_var3=tkinter.StringVar()
my_var4=tkinter.StringVar()
my_var5=tkinter.StringVar()
my_var6=tkinter.StringVar()
my_var7=tkinter.StringVar()
my_var8=tkinter.StringVar()
my_var9=tkinter.IntVar()
my_var10=tkinter.StringVar()
my_var11=tkinter.StringVar()
my_var12=tkinter.IntVar()
my_var13=tkinter.IntVar()
my_var14=tkinter.IntVar()
my_var15=tkinter.IntVar()
entry1 = tkinter.Entry(textvariable=my_var1, font=("arial", 12), borderwidth=0)
entry1.place(x=300, y=100)
entry2 = tkinter.Entry(textvariable=my_var2, font=("arial", 12), borderwidth=0)
entry2.place(x=300, y=130)
entry3 = tkinter.Entry(textvariable=my_var3, font=("arial", 12), borderwidth=0)
entry3.place(x=300, y=160)
entry4 = tkinter.Entry(textvariable=my_var4, font=("arial", 12), borderwidth=0)
entry4.place(x=300, y=190)
entry5 = tkinter.Entry(textvariable=my_var5, font=("arial", 12), borderwidth=0)
entry5.place(x=300, y=220)
entry6 = tkinter.Entry(textvariable=my_var6, font=("arial", 12), borderwidth=0)
entry6.place(x=300, y=250)
entry7 = tkinter.Entry(textvariable=my_var7, font=("arial", 12), borderwidth=0)
entry7.place(x=300, y=280)
entry8 = tkinter.Entry(textvariable=my_var8, font=("arial", 12), borderwidth=0)
entry8.place(x=300, y=310)
entry9 = tkinter.Entry(textvariable=my_var8, font=("arial", 12), borderwidth=0)
entry9.place(x=300, y=340)
entry10 = tkinter.Entry(textvariable=my_var10, font=("arial", 12), borderwidth=0)
entry10.place(x=300, y=370)
entry11 = tkinter.Entry(textvariable=my_var11, font=("arial", 12), borderwidth=0)
entry11.place(x=300, y=400)
entry12 = tkinter.Entry(textvariable=my_var12, font=("arial", 12), borderwidth=0)
entry12.place(x=300, y=430)
entry13 = tkinter.Entry(textvariable=my_var13, font=("arial", 12), borderwidth=0)
entry13.place(x=300, y=460)
entry14 = tkinter.Entry(textvariable=my_var14, font=("arial", 12), borderwidth=0)
entry14.place(x=300, y=490)
entry15 = tkinter.Entry(textvariable=my_var15, font=("arial", 12), borderwidth=0)
entry15.place(x=300, y=520)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=100)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=130)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=160)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=190)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=220)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=250)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=280)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=310)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=340)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=370)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=400)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=430)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=460)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=490)
label1=tkinter.Label(text="Age",font=("arial,12"),borderwidth=0)
label1.place(x=100,y=520)
class Interface:
    def __init__(self):
        self.label_yes=tkinter.Label()
        self.label_no=tkinter.Label()
        self.label_thank=tkinter.Label()
    def predict(self):
        self.var1=my_var1.get()
        self.var2=my_var2.get() 
        self.var3=my_var3.get()
        self.var4=my_var4.get()
        self.var5=my_var5.get()
        self.var6=my_var6.get()
        self.var7=my_var7.get()
        self.var8=my_var8.get()
        self.var9=my_var9.get()
        self.var10=my_var10.get()
        self.var11=my_var11.get()
        self.var12=my_var12.get()
        self.var13=my_var13.get()
        self.var14=my_var14.get()
        self.array=np.array([self.var1,self.var2,self.var3,self.var4,self.var5,self.my_var6,
            self.var7,self.var8,self.var9,self.var10,self.var11,self.var11,self.var12,self.var13,
            self.var14])
        lab=LabelEncoder()
        stand=StandardScaler()
        self.array1=lab.fit_transform(self.array)
        self.array2=stand.fit_transform(self.array1)
        y_pred=svm.predict(self.array2)
        if y_pred == 1:
            self.label_yes = tkinter.Label(
                text="Yes", font=("arial", 15), borderwidth=0)
            self.label1.place(x=800, y=600)
        else:
            self.label_no = tkinter.Label(
                text="No", font=("arial", 15), borderwidth=0)
            self.label2.place(x=800, y=600)
    def reset(self):
        entry1.delete(0,tkinter.END)
        entry2.delete(0,tkinter.END)
        entry3.delete(0,tkinter.END)
        entry4.delete(0,tkinter.END)
        entry5.delete(0,tkinter.END)
        entry6.delete(0,tkinter.END)
        entry7.delete(0,tkinter.END)
        entry8.delete(0,tkinter.END)
        entry9.delete(0,tkinter.END)
        entry10.delete(0,tkinter.END)
        entry11.delete(0,tkinter.END)
        entry12.delete(0,tkinter.END)
        entry13.delete(0,tkinter.END)
        entry14.delete(0,tkinter.END)
        entry15.delete(0,tkinter.END) 
    def clear(self):
        self.label_yes.after(1000,self.label_yes.destroy())
        self.label_no.after(100,self,label_no.destroy())
        self.label_thank.after(1000,self.label_thank.destroy())     
inter=Interface() 
button=tkinter.Button(text="Submit",command=inter.predict)
button.place(x=300,y=600)
button=tkinter.Button(text="Reset",command=inter.reset)
button.place(x=400,y=600)
button=tkinter.Button(text="Clear")
button.place(x=500,y=600)       
window.mainloop()